project:
  type: website
  output-dir: docs
  resources: files

website:
  title: "MuViSU"
  favicon: logo.png
  #site-url: https://github.com/MuViSU/MuViSUwebsite
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Management
        href: management.qmd
      #- text: Talks
      #  href: talks.qmd  
      #- text: Blog posts
      #  href: blog.qmd
      #- text: Publications
      #  href: publications.qmd  
    right:
      - icon: github
        href: https://github.com/      

body-footer: | 
  Copyright:  MuViSU, 2026

date-format: "D MMMM YYYY"

format:
  html:
    theme: 
      - pulse
      - custom.scss
    toc: true

